version: '3'
services:
  chromium:
    image: selenium/standalone-chromium:latest
    ports:
      - "4444:4444"
    shm_size: 2g

  scraper:
    build: .
    depends_on:
      - chromium
    environment:
      - SELENIUM_REMOTE_URL=http://chromium:4444/wd/hub
    ports:
      - "3005:3000"
    volumes:
      - .:/app
